---
title: "LDA/QDA Investigation"
output: html_document
---

```{r warning = FALSE, message = FALSE}
source("utils.R")
source("discriminant_analysis.R")
library(mvtnorm)

## Load the training and test data
train <- Load_data("./data/digits_train.txt")
test <- Load_data("./data/digits_test.txt")

x_train <- train$x
y_train <- train$y

x_test <- test$x
y_test <- test$y

priors <- Comp_priors(y_train)
means <- Comp_cond_means(x_train, y_train)
covs <- Comp_cond_covs(x_train, y_train, cov_equal = TRUE)

posteriors = Predict_posterior(x_test, priors, means, covs, TRUE)
predicted_labels = Predict_labels(posteriors)

sum(predicted_labels != y_test)/length(y_test)


```


```{r}

priors <- Comp_priors(y_train)
means <- Comp_cond_means(x_train, y_train)
covs <- Comp_cond_covs(x_train, y_train, cov_equal = FALSE)

posteriors = Predict_posterior(x_test, priors, means, covs, FALSE)
predicted_labels = Predict_labels(posteriors)

sum(predicted_labels != y_test)/length(y_test)
```


```{r warning = FALSE, message = FALSE}
library(MASS)

lda.fit = lda(y~ x, data = train)
lda.predictions = predict(lda.fit, test, type = "response")
lda.class = lda.predictions$class
mean(lda.class != test$y)

qda.fit = qda(y~ x, data = train)
qda.predictions = predict(qda.fit, test, type = "response")
qda.class = qda.predictions$class
mean(qda.class != test$y)

# LDA: 
system.time({
  priors <- Comp_priors(y_train)
  means <- Comp_cond_means(x_train, y_train)
  covs <- Comp_cond_covs(x_train, y_train, cov_equal = TRUE)
  
  posteriors = Predict_posterior(x_test, priors, means, covs, TRUE)
  predicted_labels = Predict_labels(posteriors)
  
  sum(predicted_labels != y_test)/length(y_test)
})

# QDA: 
system.time({
  priors <- Comp_priors(y_train)
  means <- Comp_cond_means(x_train, y_train)
  covs <- Comp_cond_covs(x_train, y_train, cov_equal = FALSE)
  
  posteriors = Predict_posterior(x_test, priors, means, covs, FALSE)
  predicted_labels = Predict_labels(posteriors)
  
  sum(predicted_labels != y_test)/length(y_test)
  
})

# LDA Built-In time: 0.22
system.time({
  lda.fit = lda(y~ x, data = train)
  lda.predictions = predict(lda.fit, test, type = "response")
  lda.class = lda.predictions$class
  mean(lda.class != test$y)
})

# QDA Built-In time: 0.09
system.time({
  qda.fit = qda(y~ x, data = train)
  qda.predictions = predict(qda.fit, test, type = "response")
  qda.class = qda.predictions$class
  mean(qda.class != test$y)
})
```